# Generated by Django 5.1.3 on 2024-12-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
