# Generated by Django 5.1.3 on 2025-01-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0003_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
    ]
