# Generated by Django 5.1.3 on 2025-01-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0004_delete_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
